#!/bin/sh

alias cls="clear"

alias zedit="nvim \$ZDOTDIR/.zshrc"
alias zload="source \$ZDOTDIR/.zshrc"

alias l="ls"
alias ls="eza -lah --group-directories-first --git --icons"
alias tree="eza -Ta --git-ignore"

alias ..="cd .."

alias brw="brew"
alias rbew="brew"

alias c="code"
alias c.="code ."

alias v="nvim"
alias v.="nvim ."
alias vi="nvim"
alias vim="nvim"

alias cat="bat"

alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"

alias neofetch="fastfetch -c neofetch"
alias pfetch="fastfetch -c pfetch"

# confirm before overwriting something
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

alias dpa="docker ps -a"
alias dia="docker image ls -a"
alias dva="docker volume ls"
alias dna="docker network ls"
alias ds="docker start"
alias dk="docker kill"
alias dr="docker restart"
alias dl="docker logs -f"
alias drm="docker rm"
alias dirm="docker image rm"
alias deit="docker exec -it"
alias dcu="docker compose up -d"
alias dcb="docker compose build"
alias dcd="docker compose down"
alias dcp="docker compose pull"

alias gini="git init"
alias gss="git status -s"
alias glog="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias ga="git add"
alias gaa="git add -A"
alias gcm="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gplr="git pull --rebase"
alias gf="git fetch"
alias gd="git diff"
alias gb="git branch"
alias gc="git checkout"
alias gs="git switch"

alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"

alias yt="yt-dlp"

alias zz="zellij"

alias ol="ollama"

alias z="cd"

# make a brewfile backup of all installed packages
# --force overwrites any previous Brewfile
alias brewbak="brew bundle dump --force --formula --casks --taps --file ~/.dotfiles/pkgs/Brewfile"
