#!/bin/sh

# add windows-like clear
alias cls="clear"

# edit shell configs
alias bedit="nvim ~/.bashrc"
alias zedit="nvim \$ZDOTDIR/.zshrc"
alias fedit="nvim \$XDG_CONFIG_HOME/fish/config.fish"
alias sedit="nvim \$XDG_CONFIG_HOME/shell"

# reload shell configs
alias bload="source ~/.bashrc"
alias zload="source \$ZDOTDIR/.zshrc"
alias fload="source \$XDG_CONFIG_HOME/fish/config.fish"

# go to dotfiles dir
alias dot="cd ~/.dotfiles"

# go to development dir
alias dev="cd ~/Dev"

# vscode easy
alias c="code"

# navigation
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."
alias .5="cd ../../../../.."

# replace vim and vi with neovim
alias vim="nvim"
alias vi="nvim"
alias v="nvim"

# replace cat with bat
# --paging=never makes bat act like cat
# by not piping large output's into less
alias cat="bat --paging=never"

# replace find with fd
# alias find="fd"

# replace grep with ripgrep
# alias grep="rg"

# replace ls with exa
alias l="exa -lah --group-directories-first --git --icons"
alias ls="exa -lah --group-directories-first --git --icons"

# use exa to display dir as a tree
alias tree="exa -T"

# confirm before overwriting something
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# docker
alias dpa="docker ps -a"
alias dia="docker image ls -a"
alias dva="docker volume ls"
alias dna="docker network ls"
alias ds="docker start"
alias dk="docker kill"
alias dr="docker restart"
alias dl="docker logs -f"
alias drm="docker rm"
alias dirm="docker image rm"
alias deit="docker exec -it"
alias dcu="docker compose up -d"
alias dcb="docker compose build"
alias dcd="docker compose down"
alias dcp="docker compose pull"

# git aliases
alias gini="git init"
alias gss="git status -s"
alias glog="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias ga="git add"
alias gaa="git add ."
alias gcm="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gf="git fetch"
alias gd="git diff"
alias gb="git branch"
alias gc="git checkout"

# make yarn use custom dir for .yarnrc to follow XDG spec
alias yarn="yarn --use-yarnrc '\$XDG_CONFIG_HOME/yarn/config'"

# termbin
alias tb="nc termbin.com 9999"

# yt-dlp
alias yt="yt-dlp"

# zellij
alias zz="zellij"

# open vscode in current dir
alias c="code ."

# make a brewfile backup of all installed packages
# --force overwrites any previous Brewfile
# --describe adds package description comments to Brewfile
# --file sets custom backup location. (Location must exist) (Default is current dir)
alias brewbak="brew bundle dump --force --describe --file ~/.dotfiles/pkgs/Brewfile"
