#!/usr/bin/env bash

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"

alias tree="runx eza -Ta"
alias pfetch="runx fastfetch -c pfetch"
alias neofetch="runx fastfetch -c neofetch"
alias wget="runx wget --hsts-file=\$XDG_DATA_HOME/wget-hsts"

# l -> ls
alias l="ls"
alias ls="eza -laagH \
  --group-directories-first \
  --git \
  --icons \
  --time-style '+%h %e  %Y'$'\n''%h %e %H:%M'"

alias cat="bat"

# edit shell configs
alias zedit="\$EDITOR \$ZDOTDIR"
alias fedit="\$EDITOR \$XDG_CONFIG_HOME/fish"

# homebrew
alias brw="brew"
alias rbew="brew"

# cursor easy
alias c="cursor"
alias c="cursor ."

# lazygit
alias lg="lazygit"

# bun install easy
alias buni="bun install"

# mise easy
alias mr="mise run"

# zed easy
alias z="zed-preview ."

# nvim
alias v="nvim"
alias v="nvim ."
alias vi="nvim"
alias vim="nvim"

# docker
alias dpa="docker ps -a"
alias dia="docker image ls -a"
alias dva="docker volume ls"
alias dna="docker network ls"
alias ds="docker start"
alias dk="docker kill"
alias dr="docker restart"
alias dl="docker logs -f"
alias drm="docker rm"
alias dirm="docker image rm"
alias deit="docker exec -it"
alias dcu="docker compose up -d"
alias dcb="docker compose build"
alias dcd="docker compose down"
alias dcp="docker compose pull"
alias dcl="docker compose logs -f"

alias gsp="gs"

# git
alias gss="git status -s"
alias ga="git add"
alias gaa="git add -A"
alias gap="git add -p"
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gpl="git pull"
alias gplr="git pull --rebase"
alias gf="git fetch"
alias gd="git diff"
alias gb="git branch"
alias gc="git checkout"
alias gs="git switch"
alias gsc="git switch -c"
alias gri="git rebase -i"
alias gw="git worktree"
alias gwa="git worktree add"
alias gwl="git worktree list"
alias gwr="git worktree remove"
alias glog="git log \
  --graph \
  --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
