#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state

export HOMEBREW_PREFIX=/opt/homebrew
export HOMEBREW_CELLAR=/opt/homebrew/Cellar
export HOMEBREW_REPOSITORY=/opt/homebrew
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_BAT=1
export HOMEBREW_DISPLAY_INSTALL_TIMES=1

export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$PATH"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
# these dirs must exist else zsh will not honor the session dir
export SHELL_SESSION_DIR="$XDG_STATE_HOME"/zsh/sessions
export SHELL_SESSION_FILE="$SHELL_SESSION_DIR"/"$TERM_SESSION_ID"

# set bash history file
# dir must exist else bash will not save history
export HISTFILE="$XDG_STATE_HOME"/bash/history

# set 1Password ssh-agent socket
if [[ $(uname -a) =~ Darwin ]]; then
  export SSH_AUTH_SOCK="$HOME"/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
fi

if command -v nvim &>/dev/null; then
  export EDITOR=nvim
fi

if command -v cursor &>/dev/null; then
  export VISUAL="cursor --wait"
fi

if command -v bat &>/dev/null; then
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

export LESSHISTFILE=-

export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=1

export MISE_NODE_COREPACK=1

export GNUPGHOME="$XDG_DATA_HOME"/gnupg
# load gpg keys
export GPG_TTY=$(tty)

export JJ_CONFIG="$XDG_CONFIG_HOME"/jj/config.toml

export ANDROID_HOME="$HOME"/Library/Android/sdk

export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

export DISABLE_BUN_ANALYTICS=1
export BUN_INSTALL="$XDG_DATA_HOME"/bun
export BUN_INSTALL_GLOBAL_DIR="$BUN_INSTALL"/install/global
export BUN_INSTALL_BIN="$BUN_INSTALL"/bin
export BUN_INSTALL_CACHE_DIR="$XDG_CACHE_HOME"/bun

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history

export PNPM_HOME="$XDG_DATA_HOME"/pnpm

export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

export CP_HOME_DIR="$XDG_DATA_HOME"/cocoapods

export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

export PATH="$HOME/.local/bin":"$CARGO_HOME/bin":"$BUN_INSTALL/bin":"$XDG_DATA_HOME/yarn/bin":"$PNPM_HOME":"$ANDROID_HOME/cmdline-tools/latest/bin":"$ANDROID_HOME/platform-tools":"$PATH"
