tap "beerpiss/tap"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
# Tool for reverse engineering 3rd party, closed, binary Android apps
brew "apktool"
# Automatic configure script builder
brew "autoconf"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU compiler collection
brew "gcc"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Console Matrix
brew "cmatrix"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Configurable talking characters in ASCII art
brew "cowsay"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Plugin manager for the Fish shell
brew "fisher"
# Infamous electronic fortune-cookie generator
brew "fortune"
# GitHub command-line tool
brew "gh"
# Interactive command-line tool for using emoji in commit messages
brew "gitmoji"
# Render markdown on the CLI
brew "glow"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Manage your GnuPG keys with ease! 🔐
brew "gpg-tui"
# OpenType text shaping engine
brew "harfbuzz"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Terminal file manager
brew "lf"
# JIT library for the GNU compiler collection
brew "libgccjit"
# Rainbows and unicorns in your console!
brew "lolcat"
# Mac App Store command-line interface
brew "mas"
# CLI for MySQL with auto-completion and syntax highlighting
brew "mycli"
# Open source relational database management system
brew "mysql"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Git repository summary on your terminal
brew "onefetch"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Pretty system information tool written in POSIX sh
brew "pfetch"
# File browser
brew "ranger"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Rust toolchain installer
brew "rustup-init"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Official documentation format of the GNU project
brew "texinfo"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# Flexible and fast Zsh plugin manager
brew "zinit"
# Aidoku development toolkit
brew "beerpiss/tap/aidoku-cli"
brew "d12frosted/emacs-plus/emacs-plus@28", args: ["with-modern-doom-icon", "with-native-comp"]
# Command-line tool to customize Spotify client
brew "khanhas/tap/spicetify-cli"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Application launcher and productivity software
cask "alfred"
# Enable Windows-like alt-tab
cask "alt-tab"
# Automatic tiling window manager similar to xmonad
cask "amethyst"
# Menu bar icon organizer
cask "bartender"
# Installer for BetterDiscord
cask "betterdiscord-installer"
# Desktop password and login vault
cask "bitwarden"
# Web browser focusing on privacy
cask "brave-browser"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Productivity app
cask "dropzone"
# Monospaced font that includes programming ligatures
cask "font-cascadia-code"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code-nerd-font"
# Free and open-source media player
cask "iina"
# HTTP and GraphQL Client
cask "insomnia"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Menu bar calendar
cask "itsycal"
# Jellyfin desktop client
cask "jellyfin-media-player"
# JetBrains tools manager
cask "jetbrains-toolbox"
# File archiver
cask "keka"
# Open-source keystroke visualizer
cask "keycastr"
# Web browser
cask "librewolf"
# Clipboard manager
cask "maccy"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# Remote desktop client
cask "microsoft-remote-desktop"
# Open-source software for live streaming and screen recording
cask "obs"
# QuickLook generator for Markdown files
cask "qlmarkdown"
cask "qlvideo"
# Control your tools with a few keystrokes
cask "raycast"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Quicklook extension for source files
cask "syntax-highlight"
# Open-source code editor
cask "visual-studio-code"
# Video communication and virtual meeting platform
cask "zoom"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "NordVPN", id: 905953485
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
