"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"

add_newline = false

[shlvl]
disabled = false
format = '[\[$shlvl\] ]($style)'
threshold = 2

[sudo]
format = '[$symbol ]($style)'
style = 'bold fg:yellow'
symbol = '\$UDO'
disabled = false

[character]
format = '$symbol '
success_symbol = '[❯❯❯](bold fg:green)'
error_symbol = '[❯❯❯](bold fg:red)'
vimcmd_symbol = '[❮❮❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮❮❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮❮❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮❮❮](bold fg:yellow)'
