[tools]
node = "lts"
bun = "latest"
deno = "latest"
python = "latest"
uv = "latest"
java = "zulu-21"
zig = "latest"
go = "latest"
rust = "stable"
"cargo:krabby" = "latest"
"aqua:dotenvx/dotenvx" = "latest"
"ubi:aidoku/aidoku-cli" = { version = "latest", exe = "aidoku" }
"npm:eas-cli" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"ubi:itzg/rcon-cli" = "latest"

[settings]
experimental = true
not_found_auto_install = false
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true
