[tools]
node = "lts"
bun = "latest"
deno = "latest"
python = "latest"
uv = "latest"
java = "zulu-21"
zig = "latest"
"cargo:krabby" = "latest"
"npm:eas-cli" = "latest"
"aqua:dotenvx/dotenvx" = "latest"
"ubi:aidoku/aidoku-cli" = { version = "latest", exe = "aidoku" }
go = "latest"

[settings]
experimental = true
not_found_auto_install = false

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.python]
# uv_venv_auto = true
