# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all\
$sudo$character
"""

add_newline = true

[sudo]
format = '[$symbol]($style)'
style = 'bold fg:yellow'
symbol = '❯❯❯'
disabled = false

[character]
success_symbol = '[❯❯❯](bold fg:green)'
error_symbol = '[❯❯❯](bold fg:red)'
vimcmd_symbol = '[❮❮❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮❮❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮❮❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮❮❮](bold fg:yellow)'

