[helpers]

[default]
depends = ["bash"]

# to symlink entire dirs disable recurse, a global config is planned
# ex: "fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }
[default.files]
"git" = "~/.config/git"
"setup.sh" = "~/.local/bin/bootstrap"

[hushlogin.files]
".hushlogin" = "~/.hushlogin"

[mise.files]
"mise" = "~/.config/mise"

[fastfetch.files]
"fastfetch/presets" = "~/.local/share/fastfetch/presets"

[fish]
depends = ["starship", "bin"]

[fish.files]
"fish/conf.d" = { target = "~/.config/fish/conf.d", type = "symbolic", recurse = false }
"fish/functions" = { target = "~/.config/fish/functions", type = "symbolic", recurse = false }

[zsh]
depends = ["starship", "bin", "shell"]

[zsh.files]
"zsh/.zshenv" = "~/.zshenv"
"zsh/.zshrc" = "~/.config/zsh/.zshrc"

[bash]
depends = ["starship", "bin", "shell"]

[bash.files]
"bash/.bashrc" = "~/.bashrc"
"bash/.bash_profile" = "~/.bash_profile"

[shell.files]
"shell" = "~/.config/shell"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[starshipalt.files]
"starship/starship.alt.toml" = "~/.config/starship.toml"

[node]
depends = ["mise"]

[node.files]
"yarn/.yarnrc" = "~/.yarnrc"
"npm" = "~/.config/npm"

[bun]
depends = ["mise"]

[bun.files]
"bun/.bunfig.toml" = "~/.config/.bunfig.toml"

[tmux.files]
"tmux" = "~/.config/tmux"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
"zellij/zellij-autostart" = "~/.local/bin/zellij-autostart"

[nvim.files]
"nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[zed.files]
"zed" = "~/.config/zed"

[bin.files]
"bin" = "~/.local/bin"

[warp.files]
"warp" = "~/.warp"

[ghostty.files]
"ghostty" = "~/.config/ghostty"

[atuin.files]
"atuin" = "~/.config/atuin"

[default.variables]
