[helpers]

[default]
depends = []

# to symlink entire dirs disable recurse, a global config is planned
# ex: "fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }
[default.files]
"git" = "~/.config/git"
"starship.toml" = "~/.config/starship.toml"
".hushlogin" = "~/.hushlogin"

[fish.files]
"fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }

[zsh.files]
".zshenv" = "~/.zshenv"
"zsh" = "~/.config/zsh"
"shell" = { target = "~/.config/shell", type = "symbolic", recurse = false }

[starshipalt.files]
"starship.alt.toml" = "~/.config/starship.toml"

[node.files]
"yarn" = "~/.config/yarn"
"npm" = "~/.config/npm"

[bun.files]
".bunfig.toml" = "~/.config/.bunfig.toml"

[tmux.files]
"tmux" = "~/.config/tmux"

[bin.files]
"bin" = { target = "~/.local/bin", type = "symbolic", recurse = false }

[default.variables]
