[helpers]

[default]
depends = []

[default.files]
"starship.toml" = "~/.config/starship.toml"
".zshenv" = "~/.zshenv"
"zsh" = "~/.config/zsh"
"yarn" = "~/.config/yarn"
"npm" = "~/.config/npm"

[default.variables]
