[helpers]

[default]
depends = []

# to symlink entire dirs disable recurse, a global config is planned
# ex: "fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }
[default.files]
"git" = "~/.config/git"
"starship/starship.toml" = "~/.config/starship.toml"
".hushlogin" = "~/.hushlogin"
"bat" = "~/.config/bat"
"mise" = "~/.config/mise"
"fastfetch/presets" = "~/.local/share/fastfetch/presets"

[fish.files]
"fish/conf.d" = { target = "~/.config/fish/conf.d", type = "symbolic", recurse = false }
"fish/functions" = { target = "~/.config/fish/functions", type = "symbolic", recurse = false }

[zsh.files]
"zsh/.zshenv" = "~/.zshenv"
"zsh/.zshrc" = "~/.config/zsh/.zshrc"
"shell" = "~/.config/shell"

[starshipalt.files]
"starship/starship.alt.toml" = "~/.config/starship.toml"

[node.files]
"yarn" = "~/.config/yarn"
"npm" = "~/.config/npm"

[bun.files]
"bun/.bunfig.toml" = "~/.config/.bunfig.toml"

[tmux.files]
"tmux" = "~/.config/tmux"

[nvim.files]
"nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[zed.files]
"zed" = "~/.config/zed"

[bin.files]
"bin" = "~/.local/bin"

[default.variables]
