[helpers]

[default]
depends = []

# to symlink entire dirs disable recurse, a global config is planned
# ex: "fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }
[default.files]
"git" = "~/.config/git"
"bat" = "~/.config/bat"

[hushlogin.files]
".hushlogin" = "~/.hushlogin"

[mise.files]
"mise" = "~/.config/mise"

[fastfetch.files]
"fastfetch/presets" = "~/.local/share/fastfetch/presets"

[fish]
depends = ["starship"]

[fish.files]
"fish/conf.d" = { target = "~/.config/fish/conf.d", type = "symbolic", recurse = false }
"fish/functions" = { target = "~/.config/fish/functions", type = "symbolic", recurse = false }

[zsh]
depends = ["starship"]

[zsh.files]
"zsh/.zshenv" = "~/.zshenv"
"zsh/.zshrc" = "~/.config/zsh/.zshrc"
"shell" = "~/.config/shell"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[starshipalt.files]
"starship/starship.alt.toml" = "~/.config/starship.toml"

[node]
depends = ["mise"]

[node.files]
"yarn" = "~/.config/yarn"
"npm" = "~/.config/npm"

[bun]
depends = ["mise"]

[bun.files]
"bun/.bunfig.toml" = "~/.config/.bunfig.toml"

[tmux.files]
"tmux" = "~/.config/tmux"

[nvim.files]
"nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[zed.files]
"zed" = "~/.config/zed"

[bin.files]
"bin" = "~/.local/bin"

[server.files]
"server/fish" = "~/.config/fish"

[default.variables]
