#!/bin/sh

# disable less history file
export LESSHISTFILE=-

# disable homebrew analytics
export HOMEBREW_NO_ANALYTICS=1

# gnupg
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
# load gpg keys
export GPG_TTY="$(tty)"

# # java
# export JAVA_HOME="$(dirname "$(dirname "$(asdf which java)")")"
# export JDK_HOME="$JAVA_HOME"

# flutter
export FLUTTER_ROOT="$(rtx where flutter)"

# node corepack
export COREPACK_HOME="$XDG_DATA_HOME"/node/corepack

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history

# pnpm
export PNPM_HOME="$XDG_DATA_HOME"/pnpm

# rust
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

# cocoapods
export CP_HOME_DIR="$XDG_DATA_HOME"/cocoapods

# ranger
# disable loading default ranger config, instead load local ranger config
export RANGER_LOAD_DEFAULT_RC=false

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

# path
export PATH="$HOME/.local/bin":"$CARGO_HOME/bin":"$XDG_DATA_HOME/yarn/bin":"$PNPM_HOME":"$PATH"
