#!/bin/sh

# these are used by Apple in /etc/zshrc, which is sourced before .zshrc
#
# !warning, the $XDG_STATE_HOME/zsh dir may have to exist for this to work
# not exactly sure, more testing required
export SHELL_SESSION_DIR="$XDG_STATE_HOME"/zsh/sessions
export SHELL_SESSION_FILE="$SHELL_SESSION_DIR"/"$TERM_SESSION_ID"
# set zsh history file dir
export HISTFILE="$XDG_STATE_HOME"/zsh/history

# disable less history file
export LESSHISTFILE=-

# disable homebrew analytics
export HOMEBREW_NO_ANALYTICS=1

# gnupg
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
# load gpg keys
export GPG_TTY="$(tty)"

# asdf
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME"/asdf/asdfrc
export ASDF_DATA_DIR="$XDG_DATA_HOME"/asdf

# java
export JAVA_HOME="$(dirname "$(dirname "$(asdf which java)")")"
export JDK_HOME="$JAVA_HOME"

# node corepack
export COREPACK_HOME="$XDG_DATA_HOME"/node/corepack

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history

# pnpm
export PNPM_HOME="$XDG_DATA_HOME"/pnpm

# rust
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

# cocoapods
export CP_HOME_DIR="$XDG_DATA_HOME"/cocoapods

# ranger
# disable loading default ranger config, instead load local ranger config
export RANGER_LOAD_DEFAULT_RC=false

# mysql
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history

# myCLI - fancy msql cli
export MYCLI_HISTFILE="$XDG_DATA_HOME"/mycli-history

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

# path
export PATH="$HOME/.local/bin":"$CARGO_HOME/bin":"$XDG_DATA_HOME/yarn/bin":"$PNPM_HOME":"$JAVA_HOME":"$PATH"
